
# 🌍 Lab 4: การประมวลผลข้อมูลด้วย NumPy และ GeoPandas
## วิชา GE 234 Basic Programming for Geographers

### 🎯 **วัตถุประสงค์**
1. เข้าใจการใช้ **NumPy** สำหรับการประมวลผลข้อมูลทางภูมิศาสตร์ เช่น ข้อมูล Raster และพิกัด
2. ใช้ **GeoPandas** ในการจัดการและวิเคราะห์ข้อมูลเวกเตอร์ เช่น **Shapefile**
3. สามารถดำเนินการทางสถิติกับข้อมูลพิกัดและชั้นข้อมูลทางภูมิศาสตร์ได้
4. สามารถใช้ NumPy และ GeoPandas ร่วมกันเพื่อวิเคราะห์ข้อมูลได้

---

## 🔹 ตัวอย่างที่ 1: ใช้ NumPy คำนวณข้อมูล NDVI จากภาพ Raster


In [9]:

import numpy as np

# สร้างข้อมูลตัวอย่างสำหรับภาพ NDVI (Normalized Difference Vegetation Index)
nir = np.array([[0.7, 0.8, 0.6], [0.9, 0.5, 0.3], [0.4, 0.7, 0.2]])
red = np.array([[0.3, 0.4, 0.2], [0.5, 0.3, 0.1], [0.2, 0.3, 0.1]])

# คำนวณค่า NDVI
ndvi = (nir - red) / (nir + red)

print("ค่า NDVI:")
print(ndvi)


ค่า NDVI:
[[0.4        0.33333333 0.5       ]
 [0.28571429 0.25       0.5       ]
 [0.33333333 0.4        0.33333333]]



## 🔹 ตัวอย่างที่ 2: ใช้ NumPy คำนวณค่าเฉลี่ยและค่ามากสุดของ NDVI


In [10]:

print(f"ค่าเฉลี่ย NDVI: {np.mean(ndvi):.2f}")
print(f"ค่า NDVI สูงสุด: {np.max(ndvi):.2f}")
print(f"ค่า NDVI ต่ำสุด: {np.min(ndvi):.2f}")


ค่าเฉลี่ย NDVI: 0.37
ค่า NDVI สูงสุด: 0.50
ค่า NDVI ต่ำสุด: 0.25



## 🔹 ตัวอย่างที่ 3: ใช้ GeoPandas โหลดและวิเคราะห์ข้อมูล Shapefile


In [11]:

import geopandas as gpd

# โหลดข้อมูลชั้นข้อมูลจังหวัดของประเทศไทย
gdf = gpd.read_file("https://data.opendevelopmentmekong.net/dataset/64ee3517-4e16-418f-81da-722c123ddacd/resource/ed6ff6ec-fbe6-43a5-99f1-e057c2796c33/download/th_province_boundary.shp")

# แสดงข้อมูล 5 แถวแรก
print(gdf.head())


HTTPError: HTTP Error 404: NOT FOUND


## 🔹 ตัวอย่างที่ 4: คำนวณพื้นที่ของแต่ละจังหวัด


In [12]:

# ตรวจสอบค่า CRS (Coordinate Reference System)
print(gdf.crs)

# คำนวณพื้นที่ของแต่ละจังหวัด (หน่วยเป็นตารางเมตร)
gdf["area_sqkm"] = gdf.geometry.area / 1e6

# แสดงพื้นที่จังหวัด 5 อันดับแรกที่ใหญ่ที่สุด
print(gdf.nlargest(5, "area_sqkm")[["PROV_NAME", "area_sqkm"]])


EPSG:32647


KeyError: "['PROV_NAME'] not in index"


## 🔹 ตัวอย่างที่ 5: ใช้ GeoPandas ทำ Spatial Join


In [13]:

# โหลดข้อมูลชั้นข้อมูลอำเภอ
gdf_districts = gpd.read_file("https://data.opendevelopmentmekong.net/dataset/ed8e818c-e1e3-4746-a7cd-6e437c078b9d/resource/9db5a579-2673-4e83-bf4f-bc7a83316c35/download/th_district_boundary.shp")

# ทำ Spatial Join ระหว่างอำเภอกับจังหวัด
gdf_joined = gpd.sjoin(gdf_districts, gdf, how="inner", predicate="within")

# แสดงตัวอย่างข้อมูลที่เชื่อมโยงกัน
print(gdf_joined.head())


HTTPError: HTTP Error 404: NOT FOUND


# 📝 **กิจกรรมในแลป**

1. **แบบฝึกหัด 1**: ใช้ NumPy คำนวณค่า **Mean, Max, Min** ของค่า NDVI ในอาร์เรย์ที่สร้างขึ้นเอง
2. **แบบฝึกหัด 2**: ใช้ GeoPandas โหลด **Shapefile** ของจังหวัด และคำนวณพื้นที่ของแต่ละจังหวัด
3. **แบบฝึกหัด 3**: ใช้ GeoPandas ทำ **Spatial Join** ระหว่างข้อมูลจังหวัดและอำเภอ
4. **แบบฝึกหัด 4**: ใช้ NumPy และ GeoPandas ร่วมกันเพื่อหาข้อมูลจังหวัดที่มี NDVI เฉลี่ยสูงสุด


**แบบฝึกหัด 1**

In [14]:
import numpy as np

nir = np.array([
    [0.6, 0.7, 0.8],
    [0.5, 0.9, 0.4],
    [0.3, 0.6, 0.2]
])

red = np.array([
    [0.2, 0.3, 0.4],
    [0.2, 0.4, 0.2],
    [0.1, 0.2, 0.1]
])

ndvi = (nir - red) / (nir + red)

print("NDVI:\n", ndvi)

print("Mean:", np.mean(ndvi))
print("Max:", np.max(ndvi))
print("Min:", np.min(ndvi))

NDVI:
 [[0.5        0.4        0.33333333]
 [0.42857143 0.38461538 0.33333333]
 [0.5        0.5        0.33333333]]
Mean: 0.41257631257631255
Max: 0.49999999999999994
Min: 0.3333333333333333


**แบบฝึกหัด 2**

In [15]:
import geopandas as gpd

gdf = gpd.read_file("https://raw.githubusercontent.com/chingchai/OpenGISData-Thailand/master/provinces.geojson")

gdf = gdf.to_crs(epsg=32647)
gdf["area_sqkm"] = gdf.geometry.area / 1e6

print(gdf.nlargest(5, "area_sqkm")[["pro_en", "area_sqkm"]])

               pro_en     area_sqkm
67         Chiang Mai  22040.459280
12  Nakhon Ratchasima  20730.508346
20       Kanchanaburi  19390.511287
4                 Tak  17305.705594
28   Ubon Ratchathani  15626.394403


**แบบฝึกหัด 3**

In [16]:
gdf_districts = gpd.read_file("https://raw.githubusercontent.com/chingchai/OpenGISData-Thailand/master/districts.geojson")

gdf_districts = gdf_districts.to_crs(epsg=32647)

gdf_joined = gpd.sjoin(
    gdf_districts,
    gdf,
    how="inner",
    predicate="within"
)

print(gdf_joined.head())

  amp_code       amp_th            amp_en pro_code_left pro_th_left  \
0     9015      สิงหนคร      Singhanakhon            90       สงขลา   
1     5307        พิชัย           Phichai            53   อุตรดิตถ์   
2     9016  คลองหอยโข่ง  Khlong Hoi Khong            90       สงขลา   
3     5308        ลับแล            Laplae            53   อุตรดิตถ์   
4     9013     ควนเนียง       Khuan Niang            90       สงขลา   

  pro_en_left reg_nesdb_left reg_royin_left  perimeter_left  area_sqkm_left  \
0    Songkhla          South          South       72.908500      242.316953   
1   Uttaradit     UpperNorth          North      142.230752      696.360661   
2    Songkhla          South          South       85.990583      303.232680   
3   Uttaradit     UpperNorth          North      126.116540      467.415328   
4    Songkhla          South          South       75.657535      247.904319   

                                            geometry  index_right  \
0  MULTIPOLYGON (((672207.897

**แบบฝึกหัด 4**

In [17]:
import geopandas as gpd
import numpy as np

gdf_districts = gpd.read_file(
    "https://raw.githubusercontent.com/chingchai/OpenGISData-Thailand/master/districts.geojson"
)

np.random.seed(42)
gdf_districts["NDVI"] = np.random.rand(len(gdf_districts))

ndvi_mean = gdf_districts.groupby("pro_en")["NDVI"].mean().reset_index()

top_province = ndvi_mean.loc[ndvi_mean["NDVI"].idxmax()]

print("Province with highest average NDVI:")
print(top_province)

Province with highest average NDVI:
pro_en    Nakhon Nayok
NDVI          0.822695
Name: 25, dtype: object
